apiVersion: v1
kind: Service
metadata:
  name: iperf3-server-service
spec:
  selector:
    app: iperf3-server
  clusterIP: None
  ports:
    - name: iperf3
      protocol: TCP
      port: 5201
      targetPort: 5201
